### ISSUE TITLE
PHP8+ `parse_url` treats empty vs missing differently for query and fragment

### ISSUE THREAD

**Issue by martymcguire** [aaronpk/representative-h-card-php#4]
From https://www.php.net/manual/en/function.parse-url.php#refsect1-function.parse-url-returnvalues : 

> If the component parameter is specified, parse_url() returns a string (or an int, in the case of PHP_URL_PORT) instead of an array. If the requested component doesn't exist within the given URL, null will be returned. As of PHP 8.0.0, parse_url() distinguishes absent and empty queries and fragments:
> 
> ```
> http://example.com/foo → query = null, fragment = null
> http://example.com/foo? → query = "",   fragment = null
> http://example.com/foo# → query = null, fragment = ""
> http://example.com/foo?# → query = "",   fragment = ""
> ```
> 
> Previously all cases resulted in query and fragment being null.

This change means [this test](https://github.com/indieweb/representative-h-card-php/blob/master/tests/URLTest.php#L4-L9) won't pass:

```
  public function testURLsMatch() {
    $url1 = 'http://example.com/?';
    $url2 = 'http://example.com/#';
    $match = Mf2\HCard\urls_match($url1, $url2);
    $this->assertTrue($match);
  }
```

Previously, `urls_match` wasn't actually used outside of these tests! I have a PR to use it here: #3 

I'm not 100% on how we'd want to handle this change. Personally I'm OK treating empty query and fragment the same as if they're missing which means checking for `''` before adding them in `build_url`.

**Comment by gRegorLove** [comment]
Good catch. We can compare this specific function with [urlsMatch()](https://github.com/barnabywalters/php-mf-cleaner/blob/main/src/functions.php#L375) in php-mf-cleaner which has more recent updates and from the Github Action there, looks like it's passed tests in PHP8 and 8.1. I'm not sure it has a test for this specific case, though.

I think I agree empty and null can be treated the same. If this lib gets bumped to PHP7 minimum, `build_url` could use [null coalescing](https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op) operator in the comparisons like:

```php
$query = ($parsed_url['query'] ?? '') ? '?' . $parsed_url['query'] : '';
```

**Comment by martymcguire** [comment]
I was interested to see `urlsMatch()` in php-mf-cleaner take a different approach by using `parse_url` and comparing the set of components.

From looking at it, I initially expected it would _also_ treat `http://example.com` as different from `https://example.com/` because one will have a `path` component and one won't.

But then I looked closer and realized it's using an internal [`parseUrl()`](https://github.com/barnabywalters/php-mf-cleaner/blob/main/src/functions.php#L375) which does the same "no path? path is `/`" normalization.

> I think I agree empty and null can be treated the same. If this lib gets bumped to PHP7 minimum, build_url could use [null coalescing](https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op) operator in the comparisons like:
> 
> ```
> $query = ($parsed_url['query'] ?? '') ? '?' . $parsed_url['query'] : '';
> ```

This works for me! Though I'm also fine w/ something like `!empty($parsed_url['query'])`

**Comment by gRegorLove** [comment]
👍  That `!empty` way is probably better for readability.
